project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Olympic Swimming Bodies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exploration.qmd
        text: Explore Strokes
      - href: story.qmd
        text: Power vs Endurance
      - href: nations.qmd
        text: National Powerhouses
      - href: podium.qmd
        text: The Podium Edge
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/okhatter28/olympic-bodies
  page-footer:
    left: "© 2026 Omar Khater"
    right: "Built with Quarto & GitHub Pages"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true



